# Generated by Django 3.2.18 on 2023-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20230508_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Пользователь"),
                    ("admin", "Администратор"),
                    ("moderator", "Модератор"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
