# Generated by Django 3.2.18 on 2023-05-10 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("id",)},
        ),
    ]
